In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
data=pd.read_csv('amazon_prime_titles.csv')
data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ..."
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...
...,...,...,...,...,...,...,...,...,...,...,...,...
9663,s9664,Movie,Pride Of The Bowery,Joseph H. Lewis,"Leo Gorcey, Bobby Jordan",NaN,NaN,1940,7+,60 min,Comedy,New York City street principles get an East Si...
9664,s9665,TV Show,Planet Patrol,NaN,"DICK VOSBURGH, RONNIE STEVENS, LIBBY MORRIS, M...",NaN,NaN,2018,13+,4 Seasons,TV Shows,"This is Earth, 2100AD - and these are the adve..."
9665,s9666,Movie,Outpost,Steve Barker,"Ray Stevenson, Julian Wadham, Richard Brake, M...",NaN,NaN,2008,R,90 min,Action,"In war-torn Eastern Europe, a world-weary grou..."
9666,s9667,TV Show,Maradona: Blessed Dream,NaN,"Esteban Recagno, Ezequiel Stremiz, Luciano Vit...",NaN,NaN,2021,TV-MA,1 Season,"Drama, Sports","The series tells the story of Diego Maradona, ..."
9667,s9668,Movie,Harry Brown,Daniel Barber,"Michael Caine, Emily Mortimer, Joseph Gilgun, ...",NaN,NaN,2010,R,103 min,"Action, Drama, Suspense","Harry Brown, starring two-time Academy Award w..."

In [3]:
data.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9668 entries, 0 to 9667
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       9668 non-null   object
 1   type          9668 non-null   object
 2   title         9668 non-null   object
 3   director      7585 non-null   object
 4   cast          8435 non-null   object
 5   country       672 non-null    object
 6   date_added    155 non-null    object
 7   release_year  9668 non-null   int64
 8   rating        9331 non-null   object
 9   duration      9668 non-null   object
 10  listed_in     9668 non-null   object
 11  description   9668 non-null   object
dtypes: int64(1), object(11)
memory usage: 906.5+ KB

In [7]:
data.duplicated().sum()
data=data.drop_duplicates()

In [8]:
data.isna().sum()

show_id            0
type               0
title              0
director        2083
cast            1233
country         8996
date_added      9513
release_year       0
rating           337
duration           0
listed_in          0
description        0
dtype: int64

In [9]:
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ..."
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...

In [10]:
data.drop(['description'],axis=1,inplace=True)

In [11]:
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama"
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International"
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense"
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy"

In [12]:
data['director'].fillna('unvaliable',inplace=True)
data['cast'].fillna('unvaliable',inplace=True)
data['country']=data['country'].fillna(data['country'].mode()[0])
data['date_added']=data['date_added'].ffill()
data['rating']=data['rating'].fillna(data['rating'].mode()[0])

In [13]:
data.isna().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

In [14]:
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,13+,113 min,"Comedy, Drama"
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International"
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,13+,74 min,"Action, Drama, Suspense"
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,13+,69 min,Documentary
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,13+,45 min,"Drama, Fantasy"

In [16]:
data['date_added']=pd.to_datetime(data['date_added'], format= '%B %d, %Y')

In [17]:
data['date_added']

0      2021-03-30
1      2021-03-30
2      2021-03-30
3      2021-03-30
4      2021-03-30
          ...
9663   2021-10-10
9664   2021-10-10
9665   2021-10-10
9666   2021-10-10
9667   2021-10-10
Name: date_added, Length: 9668, dtype: datetime64[ns]

In [18]:
data['rating'].unique()

array(['13+', 'ALL', '18+', 'R', 'TV-Y', 'TV-Y7', 'NR', '16+', 'TV-PG',
       '7+', 'TV-14', 'TV-NR', 'TV-G', 'PG-13', 'TV-MA', 'G', 'PG',
       'NC-17', 'UNRATED', '16', 'AGES_16_', 'AGES_18_', 'ALL_AGES',
       'NOT_RATE'], dtype=object)

In [19]:
data['rating']=data['rating'].replace({
    "NOT_RATE":"UNRATED",
    "AGES_16_":"16+",
    "16":"16+",
    "AGES_18_":"18+"
})

In [20]:
data['rating'].unique()

array(['13+', 'ALL', '18+', 'R', 'TV-Y', 'TV-Y7', 'NR', '16+', 'TV-PG',
       '7+', 'TV-14', 'TV-NR', 'TV-G', 'PG-13', 'TV-MA', 'G', 'PG',
       'NC-17', 'UNRATED', 'ALL_AGES'], dtype=object)

In [21]:
data['type'].value_counts()

type
Movie      7814
TV Show    1854
Name: count, dtype: int64

In [22]:
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,2021-03-30,2014,13+,113 min,"Comedy, Drama"
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,2021-03-30,2018,13+,110 min,"Drama, International"
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,2021-03-30,2017,13+,74 min,"Action, Drama, Suspense"
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,2021-03-30,2014,13+,69 min,Documentary
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,2021-03-30,1989,13+,45 min,"Drama, Fantasy"

In [23]:
data.rename(columns={'listed_in':'categories'},inplace=True)
data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,categories
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,2021-03-30,2014,13+,113 min,"Comedy, Drama"
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,2021-03-30,2018,13+,110 min,"Drama, International"
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,2021-03-30,2017,13+,74 min,"Action, Drama, Suspense"
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,2021-03-30,2014,13+,69 min,Documentary
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,2021-03-30,1989,13+,45 min,"Drama, Fantasy"
...,...,...,...,...,...,...,...,...,...,...,...
9663,s9664,Movie,Pride Of The Bowery,Joseph H. Lewis,"Leo Gorcey, Bobby Jordan",United States,2021-10-10,1940,7+,60 min,Comedy
9664,s9665,TV Show,Planet Patrol,unvaliable,"DICK VOSBURGH, RONNIE STEVENS, LIBBY MORRIS, M...",United States,2021-10-10,2018,13+,4 Seasons,TV Shows
9665,s9666,Movie,Outpost,Steve Barker,"Ray Stevenson, Julian Wadham, Richard Brake, M...",United States,2021-10-10,2008,R,90 min,Action
9666,s9667,TV Show,Maradona: Blessed Dream,unvaliable,"Esteban Recagno, Ezequiel Stremiz, Luciano Vit...",United States,2021-10-10,2021,TV-MA,1 Season,"Drama, Sports"
9667,s9668,Movie,Harry Brown,Daniel Barber,"Michael Caine, Emily Mortimer, Joseph Gilgun, ...",United States,2021-10-10,2010,R,103 min,"Action, Drama, Suspense"

In [24]:
data['duration_min']=data['duration'].apply(lambda x:int(x.split()[0]) if 'min' in x else 0)

In [41]:
data['duration_season']=data['duration'].apply(lambda x:int(x.split()[0]) if 'Seasons' in x else 0)

In [42]:
data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,categories,duration_min,duration_season,month,year
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,2021-03-30,2014,13+,113 min,"Comedy, Drama",113,0,3,2021
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,2021-03-30,2018,13+,110 min,"Drama, International",110,0,3,2021
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,2021-03-30,2017,13+,74 min,"Action, Drama, Suspense",74,0,3,2021
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,2021-03-30,2014,13+,69 min,Documentary,69,0,3,2021
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,2021-03-30,1989,13+,45 min,"Drama, Fantasy",45,0,3,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9663,s9664,Movie,Pride Of The Bowery,Joseph H. Lewis,"Leo Gorcey, Bobby Jordan",United States,2021-10-10,1940,7+,60 min,Comedy,60,0,10,2021
9664,s9665,TV Show,Planet Patrol,unvaliable,"DICK VOSBURGH, RONNIE STEVENS, LIBBY MORRIS, M...",United States,2021-10-10,2018,13+,4 Seasons,TV Shows,0,4,10,2021
9665,s9666,Movie,Outpost,Steve Barker,"Ray Stevenson, Julian Wadham, Richard Brake, M...",United States,2021-10-10,2008,R,90 min,Action,90,0,10,2021
9666,s9667,TV Show,Maradona: Blessed Dream,unvaliable,"Esteban Recagno, Ezequiel Stremiz, Luciano Vit...",United States,2021-10-10,2021,TV-MA,1 Season,"Drama, Sports",0,0,10,2021
9667,s9668,Movie,Harry Brown,Daniel Barber,"Michael Caine, Emily Mortimer, Joseph Gilgun, ...",United States,2021-10-10,2010,R,103 min,"Action, Drama, Suspense",103,0,10,2021

In [28]:
filterd_actor=data[data['cast']!= 'unvaliable']
top_actor= filterd_actor['cast'].value_counts().head(10).to_frame()
top_actor

                                  count
cast
Maggie Binkley                       56
1                                    34
Anne-Marie Newland                   24
Cassandra Peterson                   21
Grace Tamayo, Erin Webbs             17
Gene Autry, Champion, Gail Davis     12
Stevin John                          11
Gallagher                             9
LB, Aaron Michael                     9
Eddie Izzard                          9

In [29]:
Country= data['country'].value_counts().to_frame()
Country

                                       count
country
United States                           9249
India                                    229
United Kingdom                            28
Canada                                    16
United Kingdom, United States             12
...                                      ...
United States, Germany, Brazil, Italy      1
South Africa                               1
Australia, United States, Germany          1
Germany, Austria, United States            1
Italy, Spain                               1

[86 rows x 1 columns]

In [30]:
rating= data['rating'].value_counts().to_frame()
rating

          count
rating
13+        2454
16+        1550
ALL        1268
18+        1246
R          1010
PG-13       393
7+          385
PG          253
NR          223
TV-14       208
TV-PG       169
TV-NR       105
G            93
TV-G         81
TV-MA        77
TV-Y         74
TV-Y7        39
UNRATED      36
NC-17         3
ALL_AGES      1

In [31]:
data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,categories,duration_min,duration_season
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,2021-03-30,2014,13+,113 min,"Comedy, Drama",113,0
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,2021-03-30,2018,13+,110 min,"Drama, International",110,0
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,2021-03-30,2017,13+,74 min,"Action, Drama, Suspense",74,0
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,2021-03-30,2014,13+,69 min,Documentary,69,0
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,2021-03-30,1989,13+,45 min,"Drama, Fantasy",45,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9663,s9664,Movie,Pride Of The Bowery,Joseph H. Lewis,"Leo Gorcey, Bobby Jordan",United States,2021-10-10,1940,7+,60 min,Comedy,60,0
9664,s9665,TV Show,Planet Patrol,unvaliable,"DICK VOSBURGH, RONNIE STEVENS, LIBBY MORRIS, M...",United States,2021-10-10,2018,13+,4 Seasons,TV Shows,0,0
9665,s9666,Movie,Outpost,Steve Barker,"Ray Stevenson, Julian Wadham, Richard Brake, M...",United States,2021-10-10,2008,R,90 min,Action,90,0
9666,s9667,TV Show,Maradona: Blessed Dream,unvaliable,"Esteban Recagno, Ezequiel Stremiz, Luciano Vit...",United States,2021-10-10,2021,TV-MA,1 Season,"Drama, Sports",0,0
9667,s9668,Movie,Harry Brown,Daniel Barber,"Michael Caine, Emily Mortimer, Joseph Gilgun, ...",United States,2021-10-10,2010,R,103 min,"Action, Drama, Suspense",103,0

In [32]:
data['month']=data['date_added'].dt.month

In [33]:
data['year']=data['date_added'].dt.year

In [34]:
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,categories,duration_min,duration_season,month,year
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,2021-03-30,2014,13+,113 min,"Comedy, Drama",113,0,3,2021
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,2021-03-30,2018,13+,110 min,"Drama, International",110,0,3,2021
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,2021-03-30,2017,13+,74 min,"Action, Drama, Suspense",74,0,3,2021
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,2021-03-30,2014,13+,69 min,Documentary,69,0,3,2021
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,2021-03-30,1989,13+,45 min,"Drama, Fantasy",45,0,3,2021

In [36]:
pd.crosstab(data['country'],data['type'])

type                                       Movie  TV Show
country
Afghanistan, France                            1        0
Australia                                      4        0
Australia, Colombia, United Kingdom            1        0
Australia, United States, Germany              1        0
Austria                                        1        0
...                                          ...      ...
United States, United Arab Emirates            1        0
United States, United Kingdom                  6        0
United States, United Kingdom, Canada          0        1
United States, United Kingdom, Germany         1        0
United States, United Kingdom, Kazakhstan      1        0

[86 rows x 2 columns]

In [37]:
pd.crosstab(data['rating'],data['type'])

type      Movie  TV Show
rating
13+        2180      274
16+        1275      275
18+        1100      146
7+          288       97
ALL         988      280
ALL_AGES      1        0
G            93        0
NC-17         3        0
NR          194       29
PG          253        0
PG-13       393        0
R          1010        0
TV-14         0      208
TV-G          0       81
TV-MA         0       77
TV-NR         0      105
TV-PG         0      169
TV-Y          0       74
TV-Y7         0       39
UNRATED      36        0

In [38]:
grouped_type=data.groupby(['date_added','type']).size().unstack()
grouped_type

type         Movie  TV Show
date_added
2021-03-30  1995.0   1034.0
2021-04-01   736.0     21.0
2021-04-04     1.0      NaN
2021-04-10     1.0      NaN
2021-04-13    87.0      8.0
...            ...      ...
2021-10-05    13.0      2.0
2021-10-06    82.0     10.0
2021-10-07    18.0      3.0
2021-10-08    96.0     10.0
2021-10-10    23.0     10.0

[84 rows x 2 columns]

In [39]:
data.groupby("categories")["duration_min"].mean().sort_values(ascending=False)

categories
Comedy, Drama, Music Videos and Concerts                          185.0
Action, Arts, Entertainment, and Culture                          165.0
Horror, International, Science Fiction                            162.0
Action, International, Suspense                                   154.0
Fantasy, Horror                                                   152.0
                                                                  ...
Animation, International, Kids                                      0.0
Drama, Unscripted, Young Adult Audience                             0.0
Drama, Unscripted                                                   0.0
Documentary, Drama, Unscripted                                      0.0
Arts, Entertainment, and Culture, Special Interest, Unscripted      0.0
Name: duration_min, Length: 518, dtype: float64

In [40]:
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,categories,duration_min,duration_season,month,year
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,2021-03-30,2014,13+,113 min,"Comedy, Drama",113,0,3,2021
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,2021-03-30,2018,13+,110 min,"Drama, International",110,0,3,2021
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,2021-03-30,2017,13+,74 min,"Action, Drama, Suspense",74,0,3,2021
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,2021-03-30,2014,13+,69 min,Documentary,69,0,3,2021
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,2021-03-30,1989,13+,45 min,"Drama, Fantasy",45,0,3,2021

In [44]:
data.to_csv("amazonnn.csv",index=False,encoding="utf-8")